spring:
  profiles:
    include:
      - common
      - db
      - security
      - kafka
    active: prod

  kafka:
    properties:
      acks: all
      retries: 10
      retry.backoff.ms: 1000
      max.block.ms: 20000
      delivery.timeout.ms: 30000

    consumer:
      bootstrap-servers: ${KAFKA_HOST_NAME:localhost}:${KAFKA_PORT:9092}
      key-deserializer:  org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: kafka-group
      auto-offset-reset: earliest

    admin:
      properties:
        bootstrap.servers: ${KAFKA_HOST_NAME:localhost}:9092


  application:
    name: FeignClientReader

server:
  port: ${SERVER_PORT:8081}



